services:
  db:
    image: mariadb:11
    container_name: antiabuse-d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "3306:3306"
    networks:
      - copypaste

  web:
    build: ./www
    container_name: antiabuse-w
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../public:/var/www/html
      - ../app:/var/www/app
      - ../templates:/var/www/templates
      - ../uploads:/var/www/uploads
      - ../assets:/var/www/html/assets
    environment:
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URL}
    depends_on:
      - db
    networks:
      - copypaste

  nagios:
    image: jasonrivers/nagios
    platform: linux/amd64
    container_name: antiabuse-n
    restart: unless-stopped
    ports:
      - "8081:80"
      - "5666:5666"
    networks:
      - copypaste

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: antiabuse-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiYzcyMTUzMDlkZjkwNWI1MDVmZmY3MTE1NzBhOWEzMmIiLCJ0IjoiNmE2OWVjNmEtOGVlZi00ZTA0LTliN2EtYTE3ZTRiMTU2YmMyIiwicyI6IlptTTBabUkxWldVdFkyVmtOeTAwT0RKakxUa3pZelF0TjJFNFptRmhOV1l5TjJNMCJ9
    depends_on:
      - web
    networks:
      - copypaste

volumes:
  db_data:

networks:
  copypaste:
    external: true